"""empty message

Revision ID: 403231464dd1
Revises: 23a9de802d11
Create Date: 2021-02-15 10:20:03.819015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403231464dd1'
down_revision = '23a9de802d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
