"""empty message

Revision ID: 8ddb1b4b8981
Revises: fe9f44b0b2a7
Create Date: 2021-02-14 20:29:50.929054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddb1b4b8981'
down_revision = 'fe9f44b0b2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'shows', 'venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'artist', ['artist_id'], ['id'])
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
